using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Sandbox;

public partial class Core : BaseNPC
{
    [Property] public bool VJ_ID_Healable = true;
    [Property] public bool VJ_DEBUG = false;
    [Property] public bool VJ_IsBeingControlled = false;
    [Property] public bool VJ_IsBeingControlled_Tool = false;
    [Property] public object VJ_TheController = NULL;
    [Property] public object VJ_TheControllerEntity = NULL;
    [Property] public object VJ_TheControllerBullseye = NULL;
    [Property] public int SelectedDifficulty = 1;
    [Property] public object AIState = VJ_STATE_NONE;
    [Property] public int NextProcessT = 0;
    [Property] public object MedicData = {;
    [Property] public bool IsFollowing = false;
    [Property] public object FollowData = {;
    [Property] public object EnemyData = {;
    [Property] public object TurnData = {;
    [Property] public object GuardData = {;
    [Property] public bool PauseAttacks = false;
    [Property] public int AnimLockTime = 0;
    [Property] public int AnimPlaybackRate = 1;
    [Property] public object AnimModelSet = VJ.ANIM_SET_NONE;
    [Property] public int LastAnimSeed = 0;
    [Property] public object LastAnimType = VJ.ANIM_TYPE_NONE;
    [Property] public int AttackSeed = 0;
    [Property] public object AttackType = VJ.ATTACK_TYPE_NONE;
    [Property] public object AttackState = VJ.ATTACK_STATE_NONE;
    [Property] public object AttackAnim = ACT_INVALID;
    [Property] public int AttackAnimDuration = 0;
    [Property] public int AttackAnimTime = 0;
    [Property] public int NextDoAnyAttackT = 0;
    [Property] public bool IsAbleToMeleeAttack = true;
    [Property] public bool MeleeAttack_IsPropAttack = false;
    [Property] public int NextIdleTime = 0;
    [Property] public int NextWanderTime = 0;
    [Property] public int NextChaseTime = 0;
    [Property] public bool Alerted = false;
    [Property] public bool Flinching = false;
    [Property] public int NextFlinchT = 0;
    [Property] public int HealthRegenDelayT = 0;
    [Property] public int NextCombineBallDmgT = 0;
    [Property] public bool Dead = false;
    [Property] public bool GibbedOnDeath = false;
    [Property] public bool DeathAnimationCodeRan = false;
    [Property] public int TakingCoverT = 0;
    [Property] public int NextOnPlayerSightT = 0;
    [Property] public bool LastHiddenZone_CanWander = true;
    [Property] public int LastHiddenZoneT = 0;
    [Property] public int NextInvestigationMove = 0;
    [Property] public int NextInvestigateSoundT = 0;
    [Property] public int NextFootstepSoundT = 0;
    [Property] public int NextBreathSoundT = 0;
    [Property] public int NextIdleSoundT = 0;
    [Property] public int IdleSoundBlockTime = 0;
    [Property] public int NextAlertSoundT = 0;
    [Property] public int NextCallForHelpT = 0;
    [Property] public int NextCallForHelpAnimationT = 0;
    [Property] public int NextLostEnemySoundT = 0;
    [Property] public int NextAllyDeathSoundT = 0;
    [Property] public int NextKilledEnemySoundT = 0;
    [Property] public int NextDamageAllyResponseT = 0;
    [Property] public int NextDamageByPlayerSoundT = 0;
    [Property] public int NextPainSoundT = 0;
    [Property] public int MainSoundPitchValue = 0;
    [Property] public object TimersToRemove = {;
    [Property] public int LatestEnemyDistance = 0;
    [Property] public int NearestPointToEnemyDistance = 0;
    [Property] public object FootStepPitch = VJ.SET(80, 100);

}